### ISSUE TITLE
orderFrom1 parameter has no effect

### ISSUE THREAD

**Issue by Julien1138** [highsolutions/eloquent-sequence#7]
The 'orderFrom1' parameter has no effect.
Sequence always starts from 1.

**Comment by highsolutions** [comment]
Hello @Julien1138 .

Yes, sequence in database always starts from 1. Parameter `orderFrom1` doesn't concerns database attribute, but list order when we use `move` method. Probably the docs aren't very clear in that sense. 

There is no need to set different starting value for `sequence` attribute, because it's only used for ordering things. In next versions we will make docs more clear in that case.

Thank you for bringing this up, anyway.
